# DATOS MONITOR_ONTS 
MAP_IP="10.180.249.28"
MAP_PUERTO="3010"
MAP_USUARIO="admin_dba"
MAP_CONTRASENA="oHc3Qoz5ILCXxX5kCh"
MAP_BD="Monitor_Onts"
MA_CONEXION="mysql -h $MAP_IP -P $MAP_PUERO -u $MAP_USUARIO -p$MAP_CONTRASENA $MAP_BD"

# DATOS PDM
PDM_IP="10.180.199.207"
PDM_PUERTO="3010"
PDM_USUARIO="user_pdm"
PDM_CONTRASENA="ITSMablil2018"
PDM_BD="dbpdm"
PDM_CONEXION="mysql -h $PDM_IP -P $PDM_PUERO -u $PDM_USUARIO -p$PDM_CONTRASENA $PDM_BD"